# language: node_js
# before_install:
#   - "export DISPLAY=:99.0"
#   - "sh -e /etc/init.d/xvfb start"
# node_js:
#   - "node"

language: node_js
node_js:
 - "stable"
before_install:
 - export CHROME_BIN=chromium-browser
services:
 - xvfb
script:
 - npm install
 - npm test